/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmacistRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Insurance.Insurer;
import Business.Network.Network;
import Business.Organization.CAPatientManagementOrganization;
import Business.Organization.DrugPharmacistOrganization;
import Business.Organization.InsuranceFinanceOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Team NullPointerException
 */
public class BillPrescribedMedicineJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    public EcoSystem business;
    public DrugPharmacistOrganization organization;
    public double totalPrice;
    public double insuranceAmount;
    public int patientId;
    public ArrayList<String> medicines;

    /**
     * Creates new form BillPrescribedMedicineJPanel
     */
    public BillPrescribedMedicineJPanel() {
        initComponents();
    }

    BillPrescribedMedicineJPanel(JPanel userProcessContainer, Organization organization, EcoSystem business, double totalPrice, double insuranceAmount, int patientId, ArrayList<String> medicines) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = (DrugPharmacistOrganization) organization;
        this.business = business;
        this.totalPrice = totalPrice;
        this.insuranceAmount = insuranceAmount;
        this.patientId = patientId;
        this.medicines = medicines;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrganizationName = new javax.swing.JLabel();
        lblStatement = new javax.swing.JLabel();
        lblPaymentDueDateVal = new javax.swing.JLabel();
        lblStatementDateVal = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMedList = new javax.swing.JTable();
        lblInsuranceName = new javax.swing.JLabel();
        lblInfo1 = new javax.swing.JLabel();
        lblInfo2 = new javax.swing.JLabel();
        lblOrganizationName1 = new javax.swing.JLabel();
        lblPaymentAmt = new javax.swing.JLabel();
        lblPatientResponsibility = new javax.swing.JLabel();
        lblPatientPaid = new javax.swing.JLabel();
        lblInsPaymentAmt = new javax.swing.JLabel();
        lblBillId = new javax.swing.JLabel();
        lblBillIdValue = new javax.swing.JLabel();
        lblPaymentDueDate = new javax.swing.JLabel();
        lblStatementDate = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        lblFormTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        lblOrganizationName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblOrganizationName.setText("<value>");

        lblStatement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStatement.setText("Statement");

        lblPaymentDueDateVal.setText("<value>");

        lblStatementDateVal.setText("<value>");

        lblPatientName.setText("<value>");

        lblName.setText("Name:");

        tblMedList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name"
            }
        ));
        jScrollPane2.setViewportView(tblMedList);

        lblInsuranceName.setText("<value>");

        lblInfo1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblInfo1.setText("Insurance Information");

        lblInfo2.setText("Thank you for choosing ");

        lblOrganizationName1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblOrganizationName1.setText("<Value>");

        lblPaymentAmt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPaymentAmt.setText("<value>");

        lblPatientResponsibility.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPatientResponsibility.setText("Patient Paid");

        lblPatientPaid.setText("<value>");

        lblInsPaymentAmt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblInsPaymentAmt.setText("<value>");

        lblBillId.setText("Bill Id:");

        lblBillIdValue.setText("<value>");

        lblPaymentDueDate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPaymentDueDate.setText("Payment Due Date");

        lblStatementDate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblStatementDate.setText("Statement Date");

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        lblFormTitle.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        lblFormTitle.setText("Pharmacy Bill");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblInfo2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOrganizationName))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(lblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBillId, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(lblBillIdValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblOrganizationName1))
                        .addGap(414, 414, 414)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPaymentDueDateVal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(lblStatementDateVal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPaymentAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInfo1)
                                .addGap(36, 36, 36)
                                .addComponent(lblInsuranceName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblInsPaymentAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPaymentDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStatementDate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPatientResponsibility)
                                .addGap(68, 68, 68)
                                .addComponent(lblPatientPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(652, 652, 652))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(679, 679, 679))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblFormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOrganizationName1)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientName)
                            .addComponent(lblName))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBillIdValue)
                            .addComponent(lblBillId))
                        .addGap(109, 109, 109)
                        .addComponent(lblStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(backJButton)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInfo2)
                            .addComponent(lblOrganizationName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPaymentDueDate)
                            .addComponent(lblStatementDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPaymentDueDateVal)
                            .addComponent(lblStatementDateVal))
                        .addGap(10, 10, 10)
                        .addComponent(lblPaymentAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInsuranceName)
                            .addComponent(lblInfo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInsPaymentAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientResponsibility)
                            .addComponent(lblPatientPaid))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PharmacistWorkAreaJPanel sysAdminwjp = (PharmacistWorkAreaJPanel) component;
//        sysAdminwjp.populatePrescriptionTableAsPerRecord();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBillId;
    private javax.swing.JLabel lblBillIdValue;
    private javax.swing.JLabel lblFormTitle;
    private javax.swing.JLabel lblInfo1;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblInsPaymentAmt;
    private javax.swing.JLabel lblInsuranceName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrganizationName;
    private javax.swing.JLabel lblOrganizationName1;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPatientPaid;
    private javax.swing.JLabel lblPatientResponsibility;
    private javax.swing.JLabel lblPaymentAmt;
    private javax.swing.JLabel lblPaymentDueDate;
    private javax.swing.JLabel lblPaymentDueDateVal;
    private javax.swing.JLabel lblStatement;
    private javax.swing.JLabel lblStatementDate;
    private javax.swing.JLabel lblStatementDateVal;
    private javax.swing.JTable tblMedList;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        lblOrganizationName.setText(organization.getName());
        lblOrganizationName1.setText(organization.getName());
        lblPaymentAmt.setText(String.valueOf(totalPrice));
        lblInsPaymentAmt.setText(String.valueOf(insuranceAmount));
        lblStatementDateVal.setText(String.valueOf(new Date()));
        Calendar paymentDueDate = Calendar.getInstance();
        paymentDueDate.add(Calendar.DATE, 15);
        lblPaymentDueDateVal.setText(String.valueOf(paymentDueDate.getTime()));
        lblPatientPaid.setText(String.valueOf(totalPrice - insuranceAmount));
        Random rnd = new Random();
        int num = rnd.nextInt(999999);
        lblBillIdValue.setText(String.format("%06d", num));
        try {
            for (Network city : business.getNetworkList()) {
                for (Enterprise ep : city.getEnterpriseDirectory().getEnterpriseList()) {
                    for (Organization org : ep.getOrganizationDirectory().getOrganizationList()) {
                        if (org.getName().equals(Organization.Type.PatientManagement.getValue())) {
                            CAPatientManagementOrganization pmo = (CAPatientManagementOrganization) org;
                            for (Patient pat : pmo.getPatientDirectory().getPatientList()) {
                                if (pat.getPatientId() == patientId) {
                                    lblPatientName.setText(pat.getName());
                                }
                            }
                        }
                        if (insuranceAmount > 0) {
                            lblInsuranceName.setText("Insured");
                        } else {
                            lblInsuranceName.setText("Uninsured");
                        }
                    }
                }
            }
        } catch (Exception e) {
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblMedList.getModel();
        model.setRowCount(0);

        for (String meds : medicines) {
            Object[] row = new Object[1];
            row[0] = meds;

            model.addRow(row);
        }
    }
}
