/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CAAuthorizationRole;

import Business.EcoSystem;
import Business.Email;
import Business.Enterprise.Enterprise;
import Business.Organization.CAPatientManagementOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CAPatientAuthorizationRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Team NullPointerException
 */
public class CAAuthorizationWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CAAdminAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Patient patient;
    private CAPatientAuthorizationRequest req;
    
    public CAAuthorizationWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        loadOrganizationQue();
        loadSelfQue();
        txtAddress.setEnabled(false);
        txtCity.setEnabled(false);
        txtEmerName1.setEnabled(false);
        txtEmerName2.setEnabled(false);
        txtEmerPhone1.setEnabled(false);
        txtEmerPhone2.setEnabled(false);
        txtEmerRelationship1.setEnabled(false);
        txtEmerRelationship2.setEnabled(false);
        txtGovtId.setEnabled(false);
        txtMobileNo.setEnabled(false);
        txtName.setEnabled(false);
        txtState.setEnabled(false);
        txtZip.setEnabled(false);
    }

    public void loadOrganizationQue(){
    
            DefaultTableModel dtm = (DefaultTableModel)tblOrganization.getModel(); 
            dtm.setRowCount(0);
        for (WorkRequest request: organization.getWorkQueue().getWorkRequestList()){
            if (request instanceof CAPatientAuthorizationRequest){
              
                Object[] row = new Object[dtm.getColumnCount()];
                CAPatientAuthorizationRequest req = ((CAPatientAuthorizationRequest)request);
                row[0]= req.getMessage();
                row[1]=req.getSender();
                row[2]= req.getReceiver();
                row[3]=req.getRequestDate();
                row[4]=req.getStatus();
                row[5]=req;
                
                dtm.addRow(row);
                        
            }
        }
    
    }
    
    
        public void loadSelfQue(){
                    DefaultTableModel dtm = (DefaultTableModel)tblMyTask.getModel(); 
                dtm.setRowCount(0);
        for (WorkRequest request: account.getWorkQueue().getWorkRequestList()){
            if (request instanceof CAPatientAuthorizationRequest){
                CAPatientAuthorizationRequest req = ((CAPatientAuthorizationRequest)request);
                if (req.getReceiver() == account){

                Object[] row = new Object[dtm.getColumnCount()];                
                row[0]= req.getMessage();
                row[1]=req.getSender();
                row[2]= req.getReceiver();
                row[3]=req.getRequestDate();
                row[4]=req.getStatus();
                row[5]=req;
                dtm.addRow(row);
                }        
            }
        }
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblGreeting = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganization = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMyTask = new javax.swing.JTable();
        btnAssignToMe = new javax.swing.JButton();
        btnAssignToPool = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnViewRequest = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMobileNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGovtId = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtEmerName1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEmerRelationship1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtEmerPhone1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEmerName2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEmerRelationship2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtEmerPhone2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        btnApproved = new javax.swing.JButton();
        btnDecline = new javax.swing.JButton();
        txtDeclineReason = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setText("User");

        lblGreeting.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGreeting.setText("Welcome");

        tblOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Request Date", "Status", "Patient"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrganization);

        tblMyTask.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Request Date", "Status", "Patient"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMyTask);

        btnAssignToMe.setText("Assign to Me >>");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });

        btnAssignToPool.setText("<< Assign to pool");
        btnAssignToPool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToPoolActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Organization Pool: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("My Task:");

        btnViewRequest.setText("View Request");
        btnViewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Request Details:");

        jLabel4.setText("Name: ");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel5.setText("Address: ");

        jLabel6.setText("City:");

        jLabel7.setText("State:");

        jLabel8.setText("Zip:");

        jLabel9.setText("Mobile no:");

        jLabel10.setText("Govt ID:");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel11.setText("Emergency Contact 1:");

        jLabel12.setText("Name: ");

        txtEmerName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmerName1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Relationship:");

        txtEmerRelationship1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmerRelationship1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Phone:");

        txtEmerPhone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmerPhone1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Name: ");

        txtEmerName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmerName2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Relationship:");

        txtEmerRelationship2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmerRelationship2ActionPerformed(evt);
            }
        });

        jLabel17.setText("Phone:");

        txtEmerPhone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmerPhone2ActionPerformed(evt);
            }
        });

        jLabel18.setText("Emergency Contact 2:");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel19.setText("Photo: ");

        btnApproved.setText("Approve ");
        btnApproved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovedActionPerformed(evt);
            }
        });

        btnDecline.setText("Decline");
        btnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineActionPerformed(evt);
            }
        });

        jLabel20.setText("Enter Decline Reason:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAssignToPool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAssignToMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewRequest))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblGreeting)
                                .addGap(18, 18, 18)
                                .addComponent(lblName))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(18, 18, 18)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtZip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(24, 24, 24)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGovtId)
                                    .addComponent(txtMobileNo, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEmerName1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmerRelationship1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmerPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEmerName2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmerRelationship2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmerPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel18))
                                .addGap(28, 28, 28)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnApproved)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDeclineReason, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDecline)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGreeting, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(btnAssignToMe)
                        .addGap(64, 64, 64)
                        .addComponent(btnAssignToPool)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewRequest)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtGovtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmerName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtEmerRelationship1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmerPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmerName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtEmerRelationship2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmerPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(25, 25, 25)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApproved)
                    .addComponent(btnDecline)
                    .addComponent(txtDeclineReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        // TODO add your handling code here:
        
        int selectedRowCount = tblOrganization.getSelectedRowCount();
        int selectedRow = tblOrganization.getSelectedRow();
        if (selectedRowCount == 1){
            CAPatientAuthorizationRequest req = (CAPatientAuthorizationRequest)tblOrganization.getValueAt(selectedRow, 5);

            if(account.getWorkQueue().getWorkRequestList().contains(req)){
                JOptionPane.showMessageDialog(null, "Request has already been assigned to you");
                return;
            }
            
            if (req.getReceiver() != null){
                JOptionPane.showMessageDialog(null, "Request has already been assigned to " + req.getReceiver().getEmployee().getName());
                return; 
            }
            
            if (req.getStatus().equalsIgnoreCase("Completed")){
                JOptionPane.showMessageDialog(null, "Completed request can't be assigned to you");
                return;
            }
            req.setReceiver(account);
            account.getWorkQueue().getWorkRequestList().add(req);
            loadOrganizationQue();
            loadSelfQue();
        }
        else
        {JOptionPane.showMessageDialog(null, "Please select one row");}
    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnAssignToPoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToPoolActionPerformed
        // TODO add your handling code here:
        int selectedRowCount = tblMyTask.getSelectedRowCount();
        int selectedRow = tblMyTask.getSelectedRow();
        if (selectedRowCount == 1){
            CAPatientAuthorizationRequest req = (CAPatientAuthorizationRequest)tblMyTask.getValueAt(selectedRow, 5);
            
            if (this.req == req){
                int dialogResult = JOptionPane.showConfirmDialog (null, "Would you like to send open request back to the the pool");
                if(dialogResult == JOptionPane.YES_OPTION){
                  emptyView(); 
                } else {return;}
            }
            
            req.setReceiver(null);
            account.getWorkQueue().getWorkRequestList().remove(req);
            loadOrganizationQue();
            loadSelfQue();
        }
        else
        {JOptionPane.showMessageDialog(null, "Please select one row");}
     
        
    }//GEN-LAST:event_btnAssignToPoolActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmerName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmerName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmerName1ActionPerformed

    private void txtEmerRelationship1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmerRelationship1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmerRelationship1ActionPerformed

    private void txtEmerPhone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmerPhone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmerPhone1ActionPerformed

    private void txtEmerName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmerName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmerName2ActionPerformed

    private void txtEmerRelationship2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmerRelationship2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmerRelationship2ActionPerformed

    private void txtEmerPhone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmerPhone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmerPhone2ActionPerformed

    private void btnViewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestActionPerformed
        // TODO add your handling code here:
                int selectedRowCount = tblMyTask.getSelectedRowCount();
        int selectedRow = tblMyTask.getSelectedRow();
        if (selectedRowCount == 1){
            req = (CAPatientAuthorizationRequest)tblMyTask.getValueAt(selectedRow, 5);
            patient = req.getPatient();
            
            txtName.setText(patient.getName());
            txtAddress.setText(patient.getAddress());
            txtCity.setText(patient.getCity());
            txtState.setText(patient.getState());
            txtZip.setText(String.valueOf(patient.getZip()));
            txtMobileNo.setText(patient.getCellNo());
            txtGovtId.setText(patient.getId());
            
            txtEmerName1.setText(patient.getEmerName1());
            txtEmerName2.setText(patient.getEmerName2());
            txtEmerPhone1.setText(patient.getEmerNumber1());
            txtEmerPhone2.setText(patient.getEmerNumber2());
            txtEmerRelationship1.setText(patient.getEmerRelationship1());
            txtEmerRelationship2.setText(patient.getEmerRelationship2());
            
            if (patient.getPhoto() != null){
                ImageIcon logoPreview = new ImageIcon(patient.getPhoto());
                lblPhoto.setIcon(logoPreview);
            }
        }
        else
        {JOptionPane.showMessageDialog(null, "Please select one row from your task");}
     
        
   
        
    }//GEN-LAST:event_btnViewRequestActionPerformed

    private void btnApprovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovedActionPerformed
        // TODO add your handling code here:
        
        patient.setStatus("Approved");
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
            if (org instanceof CAPatientManagementOrganization){
                ((CAPatientManagementOrganization)org).getPatientDirectory().addPatient(patient);
            }
        }
        req.setStatus("Completed");
        account.getWorkQueue().getWorkRequestList().remove(req);
        loadOrganizationQue();
        loadSelfQue();
        String message = "Patient: "+ patient.getName() + " with patient ID: " + patient.getPatientId() + " request has been Approved." ;
        try{
        Email.sendEmail(patient.getEmail(), "Patient addition request Approved", message);}
        catch (Exception e){
            System.out.println(e);
        }finally{
            emptyView();
        }
    }//GEN-LAST:event_btnApprovedActionPerformed

    private void btnDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineActionPerformed
        // TODO add your handling code here:
        if ((txtDeclineReason.getText().equalsIgnoreCase("") || txtDeclineReason.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Kindly enter decline reason");
            return;
        }
        String reason = "Decline: " + txtDeclineReason.getText();
        patient.setStatus(reason);
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
            if (org instanceof CAPatientManagementOrganization){
                ((CAPatientManagementOrganization)org).getPatientDirectory().addPatient(patient);
            }
        }
        req.setStatus("Completed");
        account.getWorkQueue().getWorkRequestList().remove(req);
        loadOrganizationQue();
        loadSelfQue();
        String message = "Patient: "+ patient.getName() + " with patient ID: " + patient.getPatientId() + " request has been declined due to " + txtDeclineReason.getText();
        try{
        Email.sendEmail(patient.getEmail(), "Patient addition request declined", message);}
        catch (Exception e){
            System.out.println(e);
        }finally{
            emptyView();
        }
    }//GEN-LAST:event_btnDeclineActionPerformed

    private void emptyView(){
    
            req = null;
            patient = null;
            
            txtName.setText("");
            txtAddress.setText("");
            txtCity.setText("");
            txtState.setText("");
            txtZip.setText("");
            txtMobileNo.setText("");
            txtGovtId.setText("");
            
            txtEmerName1.setText("");
            txtEmerName2.setText("");
            txtEmerPhone1.setText("");
            txtEmerPhone2.setText("");
            txtEmerRelationship1.setText("");
            txtEmerRelationship2.setText(""); 
            txtDeclineReason.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproved;
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnAssignToPool;
    private javax.swing.JButton btnDecline;
    private javax.swing.JButton btnViewRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblGreeting;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JTable tblMyTask;
    private javax.swing.JTable tblOrganization;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDeclineReason;
    private javax.swing.JTextField txtEmerName1;
    private javax.swing.JTextField txtEmerName2;
    private javax.swing.JTextField txtEmerPhone1;
    private javax.swing.JTextField txtEmerPhone2;
    private javax.swing.JTextField txtEmerRelationship1;
    private javax.swing.JTextField txtEmerRelationship2;
    private javax.swing.JTextField txtGovtId;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
